//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IA.IALogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class NotificationChannel
    {
        public int Id { get; set; }
        public string NotificationType { get; set; }
        public string NotificationChannelUri { get; set; }
        public int UserId { get; set; }
    
        public virtual User User { get; set; }
    }
}
